name: Hello Cron

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minute
  workflow_dispatch:

jobs:
  say-hello:
    runs-on: ubuntu-latest
    
    env:
      ENV_TYPE: ${{ secrets.ENV_TYPE }}
      TEST_VAR: ${{ secrets.TEST_VAR }}

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Echo Hello
        run: |
          echo "hello at $(date)"
          echo "Environment Type: $ENV_TYPE"
          echo "Test Var: $TEST_VAR"
